version: '3.4'

services:
  saas-service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    working_dir: /opt/saas
    ports:
      - "8000:8000"
    environment:
      - REDIS_NETWORK=tcp
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=""
      - REDIS_DB=1
      - SCREENS_DEST=/screens
    #command: bash -c "/opt/saas/saas"
    volumes:
      - /home/eugene/Pictures/screens:/screens
    depends_on:
      - redis

  redis:
    image: "redis"
    ports:
      - "6379:6379"
    restart: always
